language: java
jdk:
 - openjdk8

script:
  - ant -f resources/build.xml

before_install:
  - wget https://repo1.maven.org/maven2/org/processing/core/3.3.6/core-3.3.6.jar
  - sudo mkdir -p /opt/processing/core/library/
  - sudo mv core-3.3.6.jar /opt/processing/core/library/core.jar
  - mkdir -p /home/travis/sketchbook/libraries
  - wget https://github.com/processing/processing-sound/releases/download/v2.2.3/sound.zip
  - unzip sound.zip -d /home/travis/sketchbook/libraries

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: distribution/scratch-latest/
  on:
    branch: master
