name: Format

on:
  push:
    branches: [ main ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v2 minimum required
      - uses: ryanbascom/googlejavaformat@v5
        with:
          args: "--replace"
          commit-message: "style: apply google format"
