name: Format

on:
  push:
    branches: [ main ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v2 minimum required
      - name: Prettier Java Format
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
