name: Deploy JavaDoc

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: ant -f resources/build.xml
  deploy:
    needs: build
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read   # to read the artifact
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      # Deploy to the github-pages environment
    concurrency:
      group: "pages"
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: distribution/javadoc
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4