name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup
        run: |
          wget https://repo1.maven.org/maven2/org/processing/core/3.3.6/core-3.3.6.jar
          sudo mkdir -p /opt/processing/core/library/
          sudo mv core-3.3.6.jar /opt/processing/core/library/core.jar
          mkdir -p /home/$USER/sketchbook/libraries
          wget https://github.com/processing/processing-sound/releases/download/v2.2.3/sound.zip
          unzip sound.zip -d /home/$USER/sketchbook/libraries

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
        run: ant -f resources/build.xml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: distribution/scratch-latest/